# typed: false
# frozen_string_literal: true

# This file is auto-generated by crab/scripts/release/update-homebrew.sh
# Do not edit manually.

class Crab < Formula
  desc "Serverless git remote helper — repositories in cloud object storage"
  homepage "https://crab.build"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/crabbuild/crab/releases/download/v1.2.0/crab-darwin-aarch64.tar.gz"
      sha256 "e5d171c5ac418a163ca43f8b20a43a0ed845cce41d6ad9251d4ffba059922eac"
    end
    on_intel do
      url "https://github.com/crabbuild/crab/releases/download/v1.2.0/crab-darwin-x86_64.tar.gz"
      sha256 "3bc09517fbb1e1a5c11dace88a81f6876179e313e96ea1fa52b119c05c2a71cc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/crabbuild/crab/releases/download/v1.2.0/crab-linux-aarch64.tar.gz"
      sha256 "d7994c1607e6585c61ed8a65b21026261f900f969d0f8c3324beb63be2015c0b"
    end
    on_intel do
      url "https://github.com/crabbuild/crab/releases/download/v1.2.0/crab-linux-x86_64.tar.gz"
      sha256 "f234c7c5dbf676a194acc7bc61af792ed8eefb37f0edd58525ab260d7f0bf2d0"
    end
  end

  def install
    bin.install "crab"
    bin.install "crab-fuse-mount"
    bin.install_symlink "crab" => "crab-nfs-mount"
    bin.install_symlink "crab" => "git-remote-crab"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/crab version")
  end
end
