# typed: false
# frozen_string_literal: true

# This file is auto-generated by crab/scripts/update-homebrew.sh
# Do not edit manually.

class Crab < Formula
  desc "Serverless git remote helper — repositories in cloud object storage"
  homepage "https://crab.build"
  version "1.0.10"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/crabbuild/crab-release/releases/download/v1.0.10/crab-darwin-aarch64.tar.gz"
      sha256 "c56f5150bd21ca64730636c73a96b2168661996ee83a72a7b37d416f42ae6529"
    end
    on_intel do
      url "https://github.com/crabbuild/crab-release/releases/download/v1.0.10/crab-darwin-x86_64.tar.gz"
      sha256 "e09ed3a548d51eab546b172be4e91d757c99fc63c62bf08bb34c4a2752c3b306"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/crabbuild/crab-release/releases/download/v1.0.10/crab-linux-aarch64.tar.gz"
      sha256 "200c11aa60e5cde6df0e1c6ee742d77ffb10a2404ef609be4b6d9a5d5f33167a"
    end
    on_intel do
      url "https://github.com/crabbuild/crab-release/releases/download/v1.0.10/crab-linux-x86_64.tar.gz"
      sha256 "5e03b99ef92b4d14c321adc5eafb1b4b5d636d3d0f48311461676af3b0b1bdec"
    end
  end

  def install
    bin.install "crab"
    bin.install "crab-fuse-mount"
    bin.install_symlink "crab" => "crab-nfs-mount"
    bin.install_symlink "crab" => "git-remote-crab"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/crab version")
  end
end
