# typed: false
# frozen_string_literal: true

# This file is auto-generated by crab/scripts/update-homebrew.sh
# Do not edit manually.

class Crab < Formula
  desc "Serverless git remote helper — repositories in cloud object storage"
  homepage "https://crab.build"
  version "1.0.11"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/crabbuild/crab-release/releases/download/v1.0.11/crab-darwin-aarch64.tar.gz"
      sha256 "eab7f93dadcaa4bc093651393f80a9388b53e2623c13026bc9038564fef050ce"
    end
    on_intel do
      url "https://github.com/crabbuild/crab-release/releases/download/v1.0.11/crab-darwin-x86_64.tar.gz"
      sha256 "31a00a75ca2863bb33ec34350f4a14bde20aa8226a743d4cbd0dbcad93f80bbe"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/crabbuild/crab-release/releases/download/v1.0.11/crab-linux-aarch64.tar.gz"
      sha256 "e51450be92794a7ec35e7c3d6c203c01e25176813156de4348e42b8fd0df480c"
    end
    on_intel do
      url "https://github.com/crabbuild/crab-release/releases/download/v1.0.11/crab-linux-x86_64.tar.gz"
      sha256 "d7a3635b48599c4f050573ad261e4b5b1df4cccee89db55ca28a7d4ec04baf7e"
    end
  end

  def install
    bin.install "crab"
    bin.install "crab-fuse-mount"
    bin.install_symlink "crab" => "crab-nfs-mount"
    bin.install_symlink "crab" => "git-remote-crab"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/crab version")
  end
end
